### ISSUE TITLE
Inclusion of the languages "pt" and "pt_BR"

### ISSUE THREAD

**Issue by Lunovox** [minetest-mods/hopper#11]
Please add the translations below:

 * https://hosted.weblate.org/projects/minetest/mod-hopper/pt/
 * https://hosted.weblate.org/projects/minetest/mod-hopper/pt_BR/

If you can not download the files, I can send them by email, or otherwise.

Thank you! =)

**Comment by FaceDeer** [comment]
[This commit](https://github.com/minetest-mods/hopper/commit/1ee79fb94ac5aebed2df70139510687e2438e967) should do it.
