### ISSUE TITLE
Feature request: lower log verbosity from ACTION to DEBUG

### ISSUE THREAD

**Issue by ronoaldo** [minetest-mods/hopper#15]
The current verbosity of logs generated by item movmenet in hopper, chute and sorter is ACTION. Since this mod can be used to automate events, it will generate a potentially large ammount of logs.

In my server, a Techpack farm managed to generate 2.8 milion log lines with almost the exact same string. This accounted for a huge ammount of logs, contributing significantly to 50G log storage ingested in my log repository.

There could be a setting to either change the log level or to disable the logs for item movement in hopper/chute/sorter. Specially because the logs don't tell what items are being moved, and the generated output has no much relevance for, say, audit details.

**Comment by ronoaldo** [comment]
Can this be also updated on Content DB? https://content.minetest.net/packages/FaceDeer/hopper/

**Comment by SmallJoker** [comment]
Apparently changes on the master branch are not picked up automatically due to existing tags. I pushed tag v1.7.2 which should shortly be available on ContentDB.
