### ISSUE TITLE
Ejecting

### ISSUE THREAD

**Issue by tacotexmex** [minetest-mods/hopper#2]
I can never get ejecting to work, no matter how I toggle the eject button. Is there a special procedure other than opening the hopper by clicking the button?

I also can't hide the button in minetest.conf, though I set hopper_eject_button to true.

**Comment by FaceDeer** [comment]
That should be all that's needed. I've tested a variety of settings and conditions locally, both in singleplayer and with a local multiplayer server, and it seems to be working.

Note that you should set the hopper_eject_button setting to "_false_" to hide the eject button, not to "true". True is what makes it appear. I recommend changing these settings via the "Advanced Settings" menu, under the "mods" section, that way there's no possibility of making a typo when doing it.

If you click the "Eject Items" button it should switch the hopper's mode, and the next time you open the hopper's formspec it should say "Don't Eject" instead. Does that happen?

Another approach to troubleshooting: try installing the Inspector mod. https://github.com/minetest-mods/inspector This gives you a tool that will show you all the details of a node in world. Click on a hopper that's been set to eject items and you should see something like this down at the bottom of the resulting pages of text:

==== meta ====
meta.fields = return {["placer"] = "singleplayer", ["eject"] = "true"}

meta.inventory = 
main :

The "placer" metadata field records the name of the user who placed the hopper, hopper's code uses that to determine whether the hopper is allowed to take or put items into locked chests and whatnot. The "eject" metadata field will hold the value "true" if the hopper's been set to eject stuff. If it hasn't been set to eject stuff (the default) then there won't be an "eject" field listed.

Is the target space actually empty? Try building a block there and then digging it away to be sure. Hopper will only eject items into a space that is "buildable_to = true", air meets this requirement.

That's all I can think of offhand for testing.  If you're still having trouble I can try making a branch of hopper that's wired up with a bunch of debugging outputs to see if perhaps something informative turns up in your log.

**Comment by tacotexmex** [comment]
Sorry for not following up. Now when I try it it works flawlessly. Thank you for taking the time for replying and making me aware of the inspector tool.
