### ISSUE TITLE
Sorter item duplication bug 

### ISSUE THREAD

**Issue by tacotexmex** [minetest-mods/hopper#5]
If one moves an item from the player inventory to the sorter filter row, then to the sorter inventory and then back to the start, the item duplicates.
![tblvtdydnr](https://cloud.githubusercontent.com/assets/25328789/25555367/5656a242-2ce5-11e7-87b4-e0c5c46e2191.gif)

This bug also disappears items when doing the same procedure "counter-clockwise".
![i9rtf2cmxj](https://cloud.githubusercontent.com/assets/25328789/25555382/a9b80944-2ce5-11e7-8e20-747851ce6413.gif)

**Comment by FaceDeer** [comment]
I forgot to add an allow_metadata_inventory_move function to properly handle item transfers between filter and storage buffer, sorry about that. Should be fixed now.
