### ISSUE TITLE
Request Weblate free hosting

### ISSUE THREAD

**Issue by lnjX** [minetest-mods/hopper#7]
Please ask for a hosting request of translations at:
https://hosted.weblate.org/hosting/

Say that you want to add it to the Minetest project.
https://hosted.weblate.org/projects/minetest/

**Comment by lnjX** [comment]
Why is nobody responding?

**Comment by FaceDeer** [comment]
I'm sorry, I sort of drifted away from Minetest modding a few months back when some other RL stuff got busy. I've been trying to pry myself away from that lately and get back into it again, and I'm starting to deal with some of the old pull requests that have accumulated. I'll look into this.

**Comment by lnjX** [comment]
RL is more important than this! :)
I'm just trying to convince some mods to use Weblate for their translations. Currently, my mods are the only ones in the official Minetest project.

See https://hosted.weblate.org/projects/minetest/.

**Comment by FaceDeer** [comment]
Eh, it's debatable. We work for a living, but it's important to remember to do that *living* stuff afterward. We work so we can play!

Which... in this case involves string localization for software projects. Huh.

Anyway, I've signed up to Weblate. I'll send a bunch of hosting requests for the various projects of mine that have been put into minetest-mods, and close this once this project gets in.

**Comment by mnh48** [comment]
I request you to update the translations, btw... xD
I've made translations through Weblate but I didn't see it getting added to the mod itself yet...
